### PR TITLE
adding create city feature

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Hi Simon, I added the city creation feature. 
It's not very polished yet but it's already working.
Next I'm thinking about hunting a bug that when the user clicks build to open the modal, sometimes the buttons don't actually reflect what she can build (after a hard refresh it works). Have you seen this too?

**Comment by sibartlett** [comment]
@guimonz Yes, I've encountered that bug. There's also another bug, where the user goes to build their first settlement, it doesn't build properly, and the user needs to refresh the page.

**Comment by ghost** [comment]
Indeed. 
I was trying to catch the first one but I still don't know exactly how is the life-cycle of that modal popup works.
But anyway, I was playing this game: http://pio.sourceforge.net/ and they have an interesting UX concept. They don't have a build button. 
The way they do it is this: mouseover on a buildable position shows the building in place (they check everything beforehand). If they click it gets built, if they mouseout then it goes back to normal.
I think this makes the game more fluid and we should do this too... what do you think?

**Comment by sibartlett** [comment]
I've seen Pioneers, but haven't had a chance to try it out yet (as I don't think they have a decent Mac build?).

The UX you describe does sound more fluid, but I do have one concern. One of the objectives for this project is to support both desktop and mobile (phone/tablet) devices, and mouseover events do not work so well on touch devices.

I'm definitely open to suggestions/ideas though! :smile: 

In regards to the life-cycle / data-flow, have you gotten yourself familiar with [Knockout](http://knockoutjs.com/)?

**Comment by ghost** [comment]
I'm not sure about the Mac build, but the Linux build works great. :-)
I get the mobile UX problem but now I think there should be a better way.

How about a build button that doesn't open a model, it's only a toggle (on/off).
Setting it on shows a layer with everything you can build with opacity 0.4.

Like if you can build a road, all buildable edges will show up in the layer.... if you can do a settlement, then all the settlements places where you can build would show them... and the same with cities. Then if you click on one of them, it gets built, the toggle goes back to off. What you think?

I haven't checked Knockout yet but I'll take a look.

**Comment by sibartlett** [comment]
I got some inspiration from this game:
- [build modal](https://www.youtube.com/watch?v=HBBZQ9Bc2Jc&t=259)
- [trade modal](https://www.youtube.com/watch?v=HBBZQ9Bc2Jc&t=188)

If we remove the build modal, we would need to address the other functions of the modal:
- it informs the user what resources are needed for each object (road, settlement, city)
- it informs the user how many more of each object can be built

Just to make it clear; I'm not against changing things - these are just my concerns. :smile:

I will try out Pioneers some time this week, to have a look at how they do things.

**Comment by ghost** [comment]
Ok I think I was counting with this kind of information being obvious to
everyone since it is to me, but you're right... it's not for new users.
Ok I think it makes sense to keep it... :-)

**Comment by sibartlett** [comment]
We could do both?

We keep the current "Build" option with modal, and introduce a "Quick Build" option which skips the modal?

**Comment by ghost** [comment]
In the end I think it makes sense... but lets not add this to v1, right?

**Comment by sibartlett** [comment]
Yeah, the main priority should be getting the game working.

**Comment by sibartlett** [comment]
I have fixed the bug where the build modal did not reflect the correct number of resources.

**Pull request merged**
